//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationSample.WP80.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthenticationSample.WP80.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a sample test for authentication using Facebook, Google, Microsoft accounts..
        /// </summary>
        public static string AboutView_AboutApp {
            get {
                return ResourceManager.GetString("AboutView_AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AboutView_AppBarEmail {
            get {
                return ResourceManager.GetString("AboutView_AppBarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string AboutView_AppBarFeedback {
            get {
                return ResourceManager.GetString("AboutView_AppBarFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string AboutView_AppbarRateIt {
            get {
                return ResourceManager.GetString("AboutView_AppbarRateIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string AboutView_AppBarShare {
            get {
                return ResourceManager.GetString("AboutView_AppBarShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string AboutView_Credits {
            get {
                return ResourceManager.GetString("AboutView_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changemailaccount@yourprovide.com.
        /// </summary>
        public static string AboutView_EmailForFeedback {
            get {
                return ResourceManager.GetString("AboutView_EmailForFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} | Version {1} - Opinion.
        /// </summary>
        public static string AboutView_Feedback {
            get {
                return ResourceManager.GetString("AboutView_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information:.
        /// </summary>
        public static string AboutView_MoreInfo {
            get {
                return ResourceManager.GetString("AboutView_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Políticas de Privacidade.
        /// </summary>
        public static string AboutView_PrivacyPolicy {
            get {
                return ResourceManager.GetString("AboutView_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is amazing!! See {0}.
        /// </summary>
        public static string AboutView_ShareEmailBody {
            get {
                return ResourceManager.GetString("AboutView_ShareEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App for WP.
        /// </summary>
        public static string AboutView_ShareEmailSubject {
            get {
                return ResourceManager.GetString("AboutView_ShareEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is amazing!!.
        /// </summary>
        public static string AboutView_ShareSocialNetwork {
            get {
                return ResourceManager.GetString("AboutView_ShareSocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string AboutView_Support {
            get {
                return ResourceManager.GetString("AboutView_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutView_Title {
            get {
                return ResourceManager.GetString("AboutView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutView_Version {
            get {
                return ResourceManager.GetString("AboutView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string AboutView_WebSite {
            get {
                return ResourceManager.GetString("AboutView_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Sample.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Sample.
        /// </summary>
        public static string LoginView_AuthenticationSample {
            get {
                return ResourceManager.GetString("LoginView_AuthenticationSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasn´t possible to do the login. Try again....
        /// </summary>
        public static string LoginView_AuthFail {
            get {
                return ResourceManager.GetString("LoginView_AuthFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication in progress....
        /// </summary>
        public static string LoginView_AuthMessage {
            get {
                return ResourceManager.GetString("LoginView_AuthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasn´t possible to do the login. Try again....
        /// </summary>
        public static string LoginView_LoginNotAllowed_Message {
            get {
                return ResourceManager.GetString("LoginView_LoginNotAllowed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginView_Title {
            get {
                return ResourceManager.GetString("LoginView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your account:.
        /// </summary>
        public static string LoginView_UserAccount {
            get {
                return ResourceManager.GetString("LoginView_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainView_AppBarAbout {
            get {
                return ResourceManager.GetString("MainView_AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MainView_AppBarLogout {
            get {
                return ResourceManager.GetString("MainView_AppBarLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string MainView_Title {
            get {
                return ResourceManager.GetString("MainView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Sample.
        /// </summary>
        public static string MessageBox_Title {
            get {
                return ResourceManager.GetString("MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
